server:
  http_listen_port: 3200

query_frontend:
  max_outstanding_per_tenant: 1000

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "tempo:4317"
        http:
          endpoint: "tempo:4318"
    jaeger:
      protocols:
        grpc:
        thrift_http:
        thrift_compact:
        thrift_binary:

storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces