global:
  scrape_interval: 1s # Default is every 1 minute.

remote_write:
- url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
  basic_auth:
    username: 1965394
    password: glc_eyJvIjoiMTMwNDQwMiIsIm4iOiJzdGFjay0xMTI0MTcyLWhtLXdyaXRlLXByb20iLCJrIjoiQVYzN2kxUzRYSU1FVUw4MzAzSWJWNzVpIiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aC0xIn19
    
scrape_configs:
  - job_name: 'opentelemetry'
    static_configs:
      - targets: ['collector:8889']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200'] 

  - job_name: 'todo'
    static_configs:
      - targets: ['todo:9494']

  
  