global:
  scrape_interval: 1s # Default is every 1 minute.

scrape_configs:
  - job_name: 'opentelemetry'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    #- targets: ['todo:9464',auth:9464]
    - targets: ['collector:8889']

  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
    - targets: ['localhost:9090']
  
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269'] 

  - job_name: 'todo'
    static_configs:
      - targets: ['todo:9494']
  
  